import { Employee, Department } from '@/types/employee';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employeeId: 'EMP001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@company.com',
    joinDate: new Date('2020-01-15'),
    department: 'Engineering',
    position: 'Senior Software Engineer',
    managerId: '2',
    profileImage: null,
    phoneNumber: '+1-555-0101',
    birthDate: new Date('1990-05-20'),
    address: '123 Main St, San Francisco, CA',
    emergencyContact: 'Jane Doe - +1-555-0102',
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    bio: 'Experienced full-stack developer with expertise in modern web technologies.',
    isActive: true,
    createdAt: new Date('2020-01-15'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    employeeId: 'EMP002',
    firstName: 'Sarah',
    lastName: 'Smith',
    email: 'sarah.smith@company.com',
    joinDate: new Date('2019-03-10'),
    department: 'Engineering',
    position: 'Engineering Manager',
    managerId: '6',
    profileImage: null,
    phoneNumber: '+1-555-0103',
    birthDate: new Date('1985-08-15'),
    address: '456 Oak Ave, San Francisco, CA',
    emergencyContact: 'Mike Smith - +1-555-0104',
    skills: ['Leadership', 'Python', 'System Architecture', 'Team Management'],
    bio: 'Engineering leader with 10+ years of experience building scalable systems.',
    isActive: true,
    createdAt: new Date('2019-03-10'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    employeeId: 'EMP003',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mike.johnson@company.com',
    joinDate: new Date('2021-06-20'),
    department: 'Marketing',
    position: 'Marketing Specialist',
    managerId: '7',
    profileImage: null,
    phoneNumber: '+1-555-0105',
    birthDate: new Date('1992-12-03'),
    address: '789 Pine St, San Francisco, CA',
    emergencyContact: 'Lisa Johnson - +1-555-0106',
    skills: ['Digital Marketing', 'Content Strategy', 'SEO', 'Analytics'],
    bio: 'Creative marketing professional focused on digital growth strategies.',
    isActive: true,
    createdAt: new Date('2021-06-20'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    employeeId: 'EMP004',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@company.com',
    joinDate: new Date('2022-02-14'),
    department: 'Design',
    position: 'UX Designer',
    managerId: '8',
    profileImage: null,
    phoneNumber: '+1-555-0107',
    birthDate: new Date('1993-04-18'),
    address: '321 Elm St, San Francisco, CA',
    emergencyContact: 'Tom Davis - +1-555-0108',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    bio: 'UX designer passionate about creating intuitive user experiences.',
    isActive: true,
    createdAt: new Date('2022-02-14'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    employeeId: 'EMP005',
    firstName: 'David',
    lastName: 'Wilson',
    email: 'david.wilson@company.com',
    joinDate: new Date('2018-09-01'),
    department: 'Sales',
    position: 'Sales Director',
    managerId: '6',
    profileImage: null,
    phoneNumber: '+1-555-0109',
    birthDate: new Date('1980-11-25'),
    address: '654 Maple Ave, San Francisco, CA',
    emergencyContact: 'Amy Wilson - +1-555-0110',
    skills: ['Sales Strategy', 'Team Leadership', 'CRM', 'Negotiation'],
    bio: 'Results-driven sales leader with proven track record of revenue growth.',
    isActive: true,
    createdAt: new Date('2018-09-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    employeeId: 'EMP006',
    firstName: 'Jennifer',
    lastName: 'Brown',
    email: 'jennifer.brown@company.com',
    joinDate: new Date('2017-04-01'),
    department: 'Executive',
    position: 'CEO',
    managerId: undefined,
    profileImage: null,
    phoneNumber: '+1-555-0111',
    birthDate: new Date('1975-09-12'),
    address: '999 Executive Blvd, San Francisco, CA',
    emergencyContact: 'Robert Brown - +1-555-0112',
    skills: ['Strategic Leadership', 'Business Development', 'Vision Setting', 'Team Building'],
    bio: 'Visionary leader with 20+ years of experience building successful companies.',
    isActive: true,
    createdAt: new Date('2017-04-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    employeeId: 'EMP007',
    firstName: 'Alex',
    lastName: 'Chen',
    email: 'alex.chen@company.com',
    joinDate: new Date('2020-08-15'),
    department: 'Marketing',
    position: 'Marketing Manager',
    managerId: '6',
    profileImage: null,
    phoneNumber: '+1-555-0113',
    birthDate: new Date('1988-03-22'),
    address: '777 Market St, San Francisco, CA',
    emergencyContact: 'Lisa Chen - +1-555-0114',
    skills: ['Brand Management', 'Digital Strategy', 'Team Leadership', 'Campaign Management'],
    bio: 'Strategic marketing leader focused on brand growth and customer acquisition.',
    isActive: true,
    createdAt: new Date('2020-08-15'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    employeeId: 'EMP008',
    firstName: 'Lisa',
    lastName: 'Taylor',
    email: 'lisa.taylor@company.com',
    joinDate: new Date('2019-11-01'),
    department: 'Design',
    position: 'Design Director',
    managerId: '6',
    profileImage: null,
    phoneNumber: '+1-555-0115',
    birthDate: new Date('1982-07-30'),
    address: '555 Design Ave, San Francisco, CA',
    emergencyContact: 'Mark Taylor - +1-555-0116',
    skills: ['Design Leadership', 'Creative Strategy', 'Team Management', 'Design Systems'],
    bio: 'Creative director with expertise in building world-class design teams.',
    isActive: true,
    createdAt: new Date('2019-11-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Executive',
    parentId: undefined,
    managerId: '6',
    level: 0,
    description: 'Executive leadership team',
    color: '#8B5CF6',
    isActive: true,
    createdAt: new Date('2017-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Engineering',
    parentId: '1',
    managerId: '2',
    level: 1,
    description: 'Software development and engineering teams',
    color: '#3B82F6',
    isActive: true,
    createdAt: new Date('2018-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Marketing',
    parentId: '1',
    managerId: '7',
    level: 1,
    description: 'Brand management and customer acquisition',
    color: '#10B981',
    isActive: true,
    createdAt: new Date('2018-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Design',
    parentId: '1',
    managerId: '8',
    level: 1,
    description: 'User experience and visual design',
    color: '#F59E0B',
    isActive: true,
    createdAt: new Date('2018-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Sales',
    parentId: '1',
    managerId: '5',
    level: 1,
    description: 'Revenue generation and customer relationships',
    color: '#EF4444',
    isActive: true,
    createdAt: new Date('2018-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];